name: contribSnake

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  push:
    branches:
    - master

jobs:
  generate:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: generate github-contribution-grid-snake.svg
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            generated/github-contribution-grid-snake.svg
            generated/github-contribution-grid-snake-dark.svg?palette=github-dark

      - name: Push to master
        uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "chore: update contribution snake"
          branch: master
          create_branch: false
          file_pattern: generated/*.svg
          commit_user_name: github-actions[bot]
          commit_user_email: 41898282+github-actions[bot]@users.noreply.github.com
          commit_author: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
